/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "tag1": {
      "key": "tag1",
      "scope": "tags",
      "path": "/tag/tag1/",
      "pageKeys": [
        "v-48972ba3"
      ]
    },
    "tag2": {
      "key": "tag2",
      "scope": "tags",
      "path": "/tag/tag2/",
      "pageKeys": [
        "v-0bf9c7e3"
      ]
    },
    "tag3": {
      "key": "tag3",
      "scope": "tags",
      "path": "/tag/tag3/",
      "pageKeys": [
        "v-ac586ffa"
      ]
    },
    "tag4": {
      "key": "tag4",
      "scope": "tags",
      "path": "/tag/tag4/",
      "pageKeys": [
        "v-6d366443"
      ]
    }
  },
  "categories": {
    "category1": {
      "key": "category1",
      "scope": "categories",
      "path": "/categories/category1/",
      "pageKeys": [
        "v-48972ba3",
        "v-0bf9c7e3"
      ]
    },
    "category2": {
      "key": "category2",
      "scope": "categories",
      "path": "/categories/category2/",
      "pageKeys": [
        "v-ac586ffa",
        "v-6d366443"
      ]
    }
  },
  "timeline": {}
}